## Free Code Camp Python Project:

> By: **Abhishek Kumar, 185540**

# Mean-Variance-Standard Deviation Calculator

**AIM: Create a function that uses Numpy to output the mean, variance, and standard deviation of the rows, columns, and elements in a 3 x 3 matrix.**

![Mean-Median-Mode](https://upload.wikimedia.org/wikipedia/commons/c/cc/Relationship_between_mean_and_median_under_different_skewness.png)



# Import Libraries

In [1]:
import numpy as np
import pandas as pd


#  Random Matrix

In [12]:
np.random.seed(22)
array = np.random.randint(10,size=(3,3))
print(array)

[[5 4 0]
 [4 6 6]
 [4 8 4]]


#### 1.  Mean-Median-Mode: 
    
1. The ***mean*** is the average of a data set.
2. The ***mode is*** the most common number in a data set.
3. The ***median*** is the middle of the set of numbers.




# Mean_Meadian_Mode of each row and column using *numpy*

In [23]:
a_mean_col = array.mean(axis=0)
print(a_mean_col," --------column wise mean")
a_mean_row = array.mean(axis=1)
print(a_mean_row," --------row wise mean")
a_median_col = np.median(array,axis=0)
print(a_median_col," ------column wise median")
a_median_row = np.median(array,axis=1)
print(a_median_row," ------row wise median")

[4.33333333 6.         3.33333333]  --------column wise mean
[3.         5.33333333 5.33333333]  --------row wise mean
[4. 6. 4.]  ------column wise median
[4. 6. 4.]  ------row wise median




![Vairance-StandardDeviation](https://cdn1.byjus.com/wp-content/uploads/2021/03/variance-and-sd-formula.png)


#### 2. Variance-Standard Deviation-Coefficient of Variation:


1. ***Variance*** is defined as the average of the squared differences from the Mean.
2. ***standard Deviation*** is a measure of how spread out numbers are.
3. ***Coefficient of Variation*** is a statistical measure of the dispersion of data points in a data series around the mean.

![Coefficient of Variation](https://www.resourcesystemsconsulting.com/wp-content/uploads/Cv.png)



# Variance-Standard Deviation-Coefficient of Variation using *numpy*

In [53]:
std_row = np.std(array,axis=0)
std_col = np.std(array,axis=1)
var_row = np.var(array,axis=0)
var_col = np.var(array,axis=1)
cov = np.cov(array)

print(std_row,"---------->std_row")
print(std_col,"---------->std_col")
print(var_row,"---------->var_row")
print(var_col,"---------->var_col")
print(cov,"---------->cov")

[0.47140452 1.63299316 2.49443826] ---------->std_row
[2.1602469  0.94280904 1.88561808] ---------->std_col
[0.22222222 2.66666667 6.22222222] ---------->var_row
[4.66666667 0.88888889 3.55555556] ---------->var_col
[[ 7.         -2.          2.        ]
 [-2.          1.33333333  1.33333333]
 [ 2.          1.33333333  5.33333333]] ---------->cov


# Algorithmic Approach

In [25]:
array.size

9

In [32]:
# length of row
row = len(array[1])
print(row)

3


In [33]:
#length of column
col = len(array[0])
print(col)

3


In [35]:
sum_row=[0,0,0]
sum_col=[0,0,0]
#for row sum
for i in range(3):
    s=0
    for j in range(3):
        s += array[i,j]
    sum_row[i] = s
#for col sum
for i in range(3):
    s=0
    for j in range(3):
        s += array[j,i]
    sum_col[i] = s

print(sum_row,"------>sum_row")
print(sum_col,"------>sum_col")

[9, 16, 16] ------>sum_row
[13, 18, 10] ------>sum_col


In [38]:
#for mean
mean_row=np.divide(sum_row,row)
mean_col=np.divide(sum_col,col)
print(mean_row,"--------->mean_row")
print(mean_col,"--------->mean_col")

[3.         5.33333333 5.33333333] --------->mean_row
[4.33333333 6.         3.33333333] --------->mean_col
